### ISSUE TITLE
Disable signup with private repositories

### ISSUE THREAD

**Issue by willdurand** [TailorDev/assignees#18]
- [x] ⚠️ existing accounts should still continue to work
- [x] it should be mentioned that private repos are supported (not free) // Email or mailing-list?

**Focus on public repos**

## Later

- [x] it should be "easy" to allow a user to use private repos
- [ ] it should be possible to downgrade plan ???
- [ ] event controller should determine if a repo can be processed

**Comment by docteurklein** [comment]
does it mean I can't use it on private repos? good idea BTW :)

**Comment by willdurand** [comment]
@docteurklein on assignees.io, I can grant you access to get private repos :)

I have added sort of feature toggles, cf. https://github.com/TailorDev/assignees/commit/0cfeebd1b9d150828fbd78407177537e65cad2d7 and https://github.com/TailorDev/assignees/commit/c5a9d32cded14195a23383f6dea2eeac8b30c04c.
